lib/gather_keys_issue_web/router.ex
defmodule GatherKeysIssueWeb.Router do
  use GatherKeysIssueWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GatherKeysIssueWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GatherKeysIssueWeb do
    pipe_through :browser

    live "/", PageLive, :index

    live "/resources", ResourceLive.Index, :index
    live "/resources/new", ResourceLive.Index, :new
    live "/resources/:id/edit", ResourceLive.Index, :edit
    live "/resources/:id", ResourceLive.Show, :show
    live "/resources/:id/show/edit", ResourceLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", GatherKeysIssueWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GatherKeysIssueWeb.Telemetry
    end
  end
end

lib/gather_keys_issue_web/live/live_helpers.ex
defmodule GatherKeysIssueWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `GatherKeysIssueWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, GatherKeysIssueWeb.ResourceLive.FormComponent,
        id: @resource.id || :new,
        action: @live_action,
        resource: @resource,
        return_to: Routes.resource_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, GatherKeysIssueWeb.ModalComponent, modal_opts)
  end
end

lib/gather_keys_issue_web/live/modal_component.ex
defmodule GatherKeysIssueWeb.ModalComponent do
  use GatherKeysIssueWeb, :live_component

  @impl true
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>" class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target="#<%= @id %>"
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @socket, @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/gather_keys_issue_web/live/page_live.ex
defmodule GatherKeysIssueWeb.PageLive do
  use GatherKeysIssueWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, query: "", results: %{})}
  end

  @impl true
  def handle_event("suggest", %{"q" => query}, socket) do
    {:noreply, assign(socket, results: search(query), query: query)}
  end

  @impl true
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end

  defp search(query) do
    if not GatherKeysIssueWeb.Endpoint.config(:code_reloader) do
      raise "action disabled when not in development"
    end

    for {app, desc, vsn} <- Application.started_applications(),
        app = to_string(app),
        String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
        into: %{},
        do: {app, vsn}
  end
end

lib/gather_keys_issue_web/live/resource_live/form_component.ex
defmodule GatherKeysIssueWeb.ResourceLive.FormComponent do
  use GatherKeysIssueWeb, :live_component

  alias GatherKeysIssue.Resources

  @impl true
  def update(%{resource: resource} = assigns, socket) do
    changeset = Resources.change_resource(resource)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"resource" => resource_params}, socket) do
    changeset =
      socket.assigns.resource
      |> Resources.change_resource(resource_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"resource" => resource_params}, socket) do
    save_resource(socket, socket.assigns.action, resource_params)
  end

  defp save_resource(socket, :edit, resource_params) do
    case Resources.update_resource(socket.assigns.resource, resource_params) do
      {:ok, _resource} ->
        {:noreply,
         socket
         |> put_flash(:info, "Resource updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_resource(socket, :new, resource_params) do
    case Resources.create_resource(resource_params) do
      {:ok, _resource} ->
        {:noreply,
         socket
         |> put_flash(:info, "Resource created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/gather_keys_issue_web/live/resource_live/index.ex
defmodule GatherKeysIssueWeb.ResourceLive.Index do
  use GatherKeysIssueWeb, :live_view

  alias GatherKeysIssue.Resources
  alias GatherKeysIssue.Resources.Resource

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :resources, list_resources())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Resource")
    |> assign(:resource, Resources.get_resource!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Resource")
    |> assign(:resource, %Resource{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Resources")
    |> assign(:resource, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    resource = Resources.get_resource!(id)
    {:ok, _} = Resources.delete_resource(resource)

    {:noreply, assign(socket, :resources, list_resources())}
  end

  defp list_resources do
    Resources.list_resources()
  end
end

lib/gather_keys_issue_web/live/resource_live/show.ex
defmodule GatherKeysIssueWeb.ResourceLive.Show do
  use GatherKeysIssueWeb, :live_view

  alias GatherKeysIssue.Resources

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:resource, Resources.get_resource!(id))}
  end

  defp page_title(:show), do: "Show Resource"
  defp page_title(:edit), do: "Edit Resource"
end

lib/gather_keys_issue_web/live/resource_live/form_component.html.leex
<h2><%= @title %></h2>

<%= f = form_for @changeset, "#",
  id: "resource-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>

  <%= label f, :description %>
  <%= text_input f, :description %>
  <%= error_tag f, :description %>

  <%= submit "Save", phx_disable_with: "Saving..." %>
</form>

lib/gather_keys_issue_web/live/resource_live/index.html.leex
<h1>Listing Resources</h1>

<%= if @live_action in [:new, :edit] do %>
  <%= live_modal @socket, GatherKeysIssueWeb.ResourceLive.FormComponent,
    id: @resource.id || :new,
    title: @page_title,
    action: @live_action,
    resource: @resource,
    return_to: Routes.resource_index_path(@socket, :index) %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="resources">
    <%= for resource <- @resources do %>
      <tr id="resource-<%= resource.id %>">
        <td><%= resource.description %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.resource_show_path(@socket, :show, resource) %></span>
          <span><%= live_patch "Edit", to: Routes.resource_index_path(@socket, :edit, resource) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: resource.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New Resource", to: Routes.resource_index_path(@socket, :new) %></span>

lib/gather_keys_issue_web/live/resource_live/show.html.leex
<h1>Show Resource</h1>

<%= if @live_action in [:edit] do %>
  <%= live_modal @socket, GatherKeysIssueWeb.ResourceLive.FormComponent,
    id: @resource.id,
    title: @page_title,
    action: @live_action,
    resource: @resource,
    return_to: Routes.resource_show_path(@socket, :show, @resource) %>
<% end %>

<ul>

  <li>
    <strong>Description:</strong>
    <%= @resource.description %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.resource_show_path(@socket, :edit, @resource), class: "button" %></span>
<span><%= live_redirect "Back", to: Routes.resource_index_path(@socket, :index) %></span>